In [9]:
import pandas as pd
pd.read_csv("/Users/chris/Desktop/ITU/3rdsem/NA/hiv/DS0001/22140-0001-Data.tsv", sep="\t")

/var/folders/yw/s572_ycn0n5d19g5p1z13l3c0000gn/T/ipykernel_10002/420460504.py:2: DtypeWarning: Columns (2,13,27,28,29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("/Users/chris/Desktop/ITU/3rdsem/NA/ICPSR_22140_2/DS0001/22140-0001-Data.tsv", sep="\t")

,RID,SAMPLE,SG,NTYPE,FRSTTYPE,IDKNOWN,LOCAL,RACE,ETHN,SEX,...,STREETS,OCC,OCCLOC,GONOEV,SYPHEV,CHLAMEV,SOURCES,FRSTYR,STUDYNUM,YOB
0,1,1,0,1,1,1,1,4,0,1,...,0,Masked,,-8,0,-8,9,1,1,1964
1,2,1,0,1,1,1,1,4,0,1,...,0,Masked,SILK SCREENING PLANT,-8,0,-8,1,1,1,1966
2,3,1,0,1,3,1,1,4,1,0,...,0,Masked,,-8,0,-8,1,1,1,1916
3,4,1,0,1,1,1,1,5,0,1,...,0,Masked,CABINET-MAKING COMPANY,-8,0,-8,,1,1,1959
4,5,1,0,1,3,1,1,4,1,0,...,0,Masked,"POWER PLANT,RANCH",-8,0,-8,4,1,1,1955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49410,143803,2,-9,3,3,1,-9,1,-8,0,...,-8,Masked,missing (out of design),0,-8,1,1,1,8,1975
49411,143805,2,-9,3,3,1,-9,1,-8,0,...,-8,Masked,missing (out of design),0,-8,1,1,1,8,1974
49412,143811,2,-9,1,1,1,1,-8,-8,-9,...,-8,Masked,missing (out of design),-9,-8,-9,,1,8,1900
49413,143813,2,-9,3,3,1,-9,-9,-8,1,...,-8,Masked,missing (out of design),0,-8,1,1,1,8,1979
49414,143829,2,-9,1,1,1,1,1,-8,0,...,-8,Masked,missing (out of design),0,-8,1,,1,8,1976